# Generated by Django 3.1.3 on 2020-11-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20200821_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='customs',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='images/avatars/'),
        ),
    ]
